# Generated by Django 3.0.3 on 2020-06-11 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_time', models.DateTimeField(verbose_name='Дата публикации')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('addition', models.TextField(verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория 1')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='members1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория 1',
                'verbose_name_plural': 'Категории 1',
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория 2')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='members2', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='adverts.Category1')),
            ],
            options={
                'verbose_name': 'Категория 2',
                'verbose_name_plural': 'Категории 2',
            },
        ),
        migrations.CreateModel(
            name='Category3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория 3')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
                ('members', models.ManyToManyField(blank=True, related_name='members3', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='adverts.Category1')),
            ],
            options={
                'verbose_name': 'Категория 3',
                'verbose_name_plural': 'Категории 3',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
