# Generated by Django 3.0.3 on 2020-06-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_auto_20200611_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category3',
            name='parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category3', to='adverts.Category2'),
        ),
    ]
