# Generated by Django 3.0.3 on 2020-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_auto_20200614_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='adverts/', verbose_name='Изображение'),
        ),
    ]
