# Generated by Django 3.0.3 on 2020-06-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0005_banner_category3'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mybanners', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
