# Generated by Django 3.0.3 on 2020-06-17 05:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0006_banner_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mybanners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(null=True, upload_to='adverts/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='pub_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 5, 7, 56, 284738, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
