# Generated by Django 3.0.3 on 2020-06-22 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0007_auto_20200617_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pub_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Описание')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myanswers', to=settings.AUTH_USER_MODEL)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='adverts.Banner')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклик',
            },
        ),
    ]
