# Generated by Django 3.0.3 on 2020-07-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adverts', '0009_auto_20200622_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproducts3', to=settings.AUTH_USER_MODEL)),
                ('cetegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adverts.Category3')),
            ],
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproducts2', to=settings.AUTH_USER_MODEL)),
                ('cetegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adverts.Category2')),
            ],
        ),
        migrations.CreateModel(
            name='Product1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myproducts1', to=settings.AUTH_USER_MODEL)),
                ('cetegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='adverts.Category1')),
            ],
        ),
    ]
