# Generated by Django 3.0.3 on 2020-07-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0010_product1_product2_product3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product1',
            options={'verbose_name': 'Подписка на категорию 1', 'verbose_name_plural': 'Подписки на категорию 1'},
        ),
        migrations.AlterModelOptions(
            name='product2',
            options={'verbose_name': 'Подписка на категорию 2', 'verbose_name_plural': 'Подписки на категорию 2'},
        ),
        migrations.AlterModelOptions(
            name='product3',
            options={'verbose_name': 'Подписка на категорию 3', 'verbose_name_plural': 'Подписки на категорию 3'},
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='cetegory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product2',
            old_name='cetegory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product3',
            old_name='cetegory',
            new_name='category',
        ),
    ]
